language: java
# use Java 8
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  services:
  - docker
  before_install:
  - docker build -d ./src/docker/dev/docker-compose.yml 
script: mvn --file ./src/pom.xml clean test -P test-consumer,test-business

